version: '3.9'
services:
    mysql:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - "./scripts/init-mysql.sql:/docker-entrypoint-initdb.d/init.sql"

    postgresql:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
        volumes:
            - "./scripts/init-postgresql.sql:/docker-entrypoint-initdb.d/init.sql"

    mariadb:
        image: mariadb
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - "./scripts/init-mariadb.sql:/docker-entrypoint-initdb.d/init.sql"

    mongodb:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        ports:
            - "27017:27017"
        volumes:
            - "./scripts/init-mongodb.js:/docker-entrypoint-initdb.d/init.js"


    redis:
        image: redis
        restart: always
        ports:
            - "6379:6379"

    mssql:
        image: mcr.microsoft.com/mssql/server
        environment:
            SA_PASSWORD: "Rootroot1"
            ACCEPT_EULA: "Y"
        restart: always
        ports:
            - "1433:1433"
        volumes:
            - "./scripts/init-mssql.sql:/docker-entrypoint-initdb.d/init.sql"
        # command: ["/bin/bash", "-c", "sleep 5 && /opt/mssql-tools/bin/sqlcmd -U sa -P Rootroot1 -i /docker-entrypoint-initdb.d/init.sql"]
